parameters:
 - name: dockerRepository
   type: string
 - name: dockerTag
   type: string

stages:
- stage: build
  displayName: build
  jobs:
  - job: buildjob
    displayName: buildjob
    pool:
     vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs: 
        targettype: inline
        script: env
   

    

 


