parameters:
 - name: dockerRepository
   displayName: DockerRepository
   type: string
   default: 'myrepo'
 - name: dockerTag
   displayName: DockerTag
   type: string
   default: 'latest'

stages:
- stage: build
  displayName: build
  jobs:
  - job: buildjob
    displayName: buildjob
    pool:
     poolName: 
     vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs: 
        targettype: inline
        script: |
          env
          ls
          pwd
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SPN-AZURE'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Login to ACR

          az acr login --name ${{ parameters.dockerRepository }}
          
   

    

 


