parameters:
 - name: dockerRepository
   displayName: DockerRepository
   type: string
   default: 'myrepo'
 - name: dockerTag
   displayName: DockerTag
   type: string
   default: 'latest'

stages:
- stage: build
  displayName: build
  jobs:
  - job: buildjob
    displayName: buildjob
    pool:
     vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs: 
        targettype: inline
        script: |
          env
          ls
          pwd
          
   

    

 


